# Tensor operations

In [2]:
%cd ..

/home/lln/Documentos/recreate_pytorch/PyNorch


## 1 - Basic operations

In [3]:
import norch

x1 = norch.Tensor([[1, 2], 
                  [3, 4]])
x2 = norch.Tensor([[4, 3], 
                  [2, 1]])

print(f"t1 =\n{x1}")
print(f"t2 =\n{x2}")

print("\nSome basic operations")
print(f"x1 + x2: \n{x1 + x2}")
print(f"x1 - x2: \n{x1 - x2}")
print(f"x1 * x2: \n{x1 * x2}")
print(f"x1 / x2: \n{x1 / x2}")
print(f"x1 / 10: \n{x1 / 10}")
print(f"x1 @ x2: \n{x1 @ x2}")
print(f"x1 ** 2: \n{x1 ** 2}")

t1 =
tensor([[1.0, 2.0,],
[3.0, 4.0,]], device="cpu", requires_grad=False)
t2 =
tensor([[4.0, 3.0,],
[2.0, 1.0,]], device="cpu", requires_grad=False)

Some basic operations
x1 + x2: 
tensor([[5.0, 5.0,],
[5.0, 5.0,]], device="cpu", requires_grad=False)
x1 - x2: 
tensor([[-3.0, -1.0,],
[1.0, 3.0,]], device="cpu", requires_grad=False)
x1 * x2: 
tensor([[4.0, 6.0,],
[6.0, 4.0,]], device="cpu", requires_grad=False)
x1 / x2: 
tensor([[0.25, 0.6666666865348816,],
[1.5, 4.0,]], device="cpu", requires_grad=False)
x1 / 10: 
tensor([[0.10000000149011612, 0.20000000298023224,],
[0.30000001192092896, 0.4000000059604645,]], device="cpu", requires_grad=False)
x1 @ x2: 
tensor([[8.0, 5.0,],
[20.0, 13.0,]], device="cpu", requires_grad=False)
x1 ** 2: 
tensor([[1.0, 4.0,],
[9.0, 16.0,]], device="cpu", requires_grad=False)


In [4]:
print(f"x1 reshape: \n{x1.reshape([1, 4])}")
print(f"x1 transpose axes: \n{x1.transpose(1, 0)}")
print(f"x1 transpose: \n{x1.T}")

print(f"x1 zeros_like: \n{x1.zeros_like()}")
print(f"x1 ones_like: \n{x1.ones_like()}")

print(f"sin(x1): \n{x1.sin()}")
print(f"cos(x1): \n{x1.cos()}")

x1 reshape: 
tensor([[1.0, 2.0, 3.0, 4.0,]], device="cpu", requires_grad=False)
x1 transpose axes: 
tensor([[1.0, 3.0,],
[2.0, 4.0,]], device="cpu", requires_grad=False)
x1 transpose: 
tensor([[1.0, 3.0,],
[2.0, 4.0,]], device="cpu", requires_grad=False)
x1 zeros_like: 
tensor([[0.0, 0.0,],
[0.0, 0.0,]], device="cpu", requires_grad=None)
x1 ones_like: 
tensor([[1.0, 1.0,],
[1.0, 1.0,]], device="cpu", requires_grad=None)
sin(x1): 
tensor([[0.8414709568023682, 0.9092974066734314,],
[0.14112000167369843, -0.756802499294281,]], device="cpu", requires_grad=False)
cos(x1): 
tensor([[0.5403022766113281, -0.416146844625473,],
[-0.9899924993515015, -0.6536436080932617,]], device="cpu", requires_grad=False)


## 2 - Autograd

In [5]:
a = norch.Tensor([
        [[1.234, 2.123], [3.635, 4.456], [5.678, 6.789]],
        [[7.890, 8.901], [9.012, 1.234], [2.345, 3.456]],
        [[4.567, 5.678], [6.789, 7.890], [8.901, 9.012]],
        [[1.234, 2.345], [3.456, 4.567], [5.678, 6.789]],
        [[7.890, 8.901], [9.012, 1.234], [2.345, 3.456]]
    ], requires_grad=True)


b = norch.Tensor([[
        [1.234, 2.123, 1.5],
        [5.678, 6.789, 1.293],
        [3.635, 4.456, 1.0202],
        [7.890, 8.901, 1.91],
    ],[
        [1.234, 2.123, 1.5],
        [5.678, 6.789, 1.293],
        [3.635, 4.456, 1.0202],
        [7.890, 8.901, 1.91],
    ],[
        [1.234, 2.123, 1.5],
        [5.678, 6.789, 1.293],
        [3.635, 4.456, 1.0202],
        [7.890, 8.901, 1.91],
    ],[
        [1.234, 2.123, 1.5],
        [5.678, 6.789, 1.293],
        [3.635, 4.456, 1.0202],
        [7.890, 8.901, 1.91],
    ],[
        [1.234, 2.123, 1.5],
        [5.678, 6.789, 1.293],
        [3.635, 4.456, 1.0202],
        [7.890, 8.901, 1.91],
    ]])

print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}\n\n")

result = b @ a
result = result.sum()
result.backward()

print(f"gradient a: {a.grad}")


a.shape: [5, 3, 2]
b.shape: [5, 4, 3]


gradient a: tensor([[
[18.437000274658203, 18.437000274658203,],
    [22.269001007080078, 22.269001007080078,],
    [5.723199844360352, 5.723199844360352,]],
[
[18.437000274658203, 18.437000274658203,],
    [22.269001007080078, 22.269001007080078,],
    [5.723199844360352, 5.723199844360352,]],
[
[18.437000274658203, 18.437000274658203,],
    [22.269001007080078, 22.269001007080078,],
    [5.723199844360352, 5.723199844360352,]],
[
[18.437000274658203, 18.437000274658203,],
    [22.269001007080078, 22.269001007080078,],
    [5.723199844360352, 5.723199844360352,]],
[
[18.437000274658203, 18.437000274658203,],
    [22.269001007080078, 22.269001007080078,],
    [5.723199844360352, 5.723199844360352,]]], device="cpu", requires_grad=None)


# Modules

In [6]:
import norch.nn as nn

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()

        self.layer1 = nn.Linear(100, 1000)
        self.sigmoid1 = nn.Sigmoid()
        self.layer2 = nn.Linear(1000, 2)
        self.sigmoid2 = nn.Sigmoid()

    def forward(self, x):
        out = self.layer1(x)
        out = self.sigmoid1(out)
        out = self.layer2(out)
        out = self.sigmoid2(out)

        return out

In [7]:
model = MyModule()
model

MyModule(
   (layer1): Linear(input_dim=100, output_dim=1000, bias=True)
   (sigmoid1): Sigmoid()
   (layer2): Linear(input_dim=1000, output_dim=2, bias=True)
   (sigmoid2): Sigmoid()
)